Update azure-pipelines-release-notes.yml for Azure Pipelines

diff --git a/.pipelines/azure-pipelines-release-notes.yml b/.pipelines/azure-pipelines-release-notes.yml
--- a/.pipelines/azure-pipelines-release-notes.yml
+++ b/.pipelines/azure-pipelines-release-notes.yml
@@ -55,8 +55,12 @@ stages:
         OutputFile: 'release_notes.json'
     - script: |
         ls -lt
+        sudo apt update
+        sudo apt install -y jq
         SOURCE_BRANCH=sonic/release-notes-t1
         TARGET_BRANCH=sonic/release-notes-main
+        # See https://dev.azure.com/msazure/One/_apis/git/repositories/Networking-acs-buildimage/pullrequests/9296449/reviewers?api-version=7.1
+        REVIEWER_ID=1b5f2f1b-141f-65e4-b96d-29a1a9a73edd
         TAG=20220531.11
         TITLE="Add SONiC release note $TAG"
         DESCRIPTION=$TITLE
@@ -70,7 +74,12 @@ stages:
         git add test
         git commit -m "test"
         git push --set-upstream origin $SOURCE_BRANCH  -f
-        curl -X POST -L -H 'Content-Type: application/json' -H 'Accept: application/json' -u :$(System.AccessToken) \
-        "$PHYNET_URL_PREFIX?api-version=5.1" \
-        -d "$BODY"
+        https://dev.azure.com/{organization}/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/reviewers/$REVIEWER_ID?api-version=7.0
+        curl -X POST -L -H 'Content-Type: application/json' -H 'Accept: application/json' -u :$(System.AccessToken) "$PHYNET_URL_PREFIX?api-version=7.0" -d "$BODY"
+        PRID=(curl -L -H 'Content-Type: application/json' -H 'Accept: application/json' -u :$(System.AccessToken) "$PHYNET_URL_PREFIX?api-version=7.0&&searchCriteria.sourceRefName=refs/heads/sonic/$SOURCE_BRANCH" | jq '.value[0].pullRequestId')
+        if [ -z "$PRID" ]; then
+            echo "Failed to query the PR" 1>&2
+            exit 1
+        fi
+        curl -X PUT -L -H 'Content-Type: application/json' -H 'Accept: application/json' -u :$(MSAZURE_TOKEN) "$PHYNET_URL_PREFIX/$PRID/reviewers/$REVIEWER_ID?api-version=7.0" -d '{"vote":10}'
       displayName: "List files"
